### ISSUE TITLE
Remove boilerplate from the Makefile

### ISSUE THREAD

**Issue by joereynolds** [paralax/ColossalOpera#33]
Currently, each file (100+) is included in the Makefile. It'd be much cleaner and easier to navigate if we just include the directory for `easy/`, `intermediate/`, and `hard` and then just iterate through those when we need to

**Comment by paralax** [comment]
I had done that earlier but there are challenges in there that are not good
for inclusion. That's why I don't do that.

Jose

Sent from my Motorola Razor

On Apr 1, 2016, at 3:04 PM, Joe Reynolds notifications@github.com wrote:

Currently, each files (100+) is included in the Makefile. It'd be much
cleaner and easier to navigate if we just include the directory for easy/,
intermediate/, and hard and then just iterate through those when we need to

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/paralax/ColossalOpera/issues/33

**Comment by joereynolds** [comment]
If they're not meant to be included can we not remove them from the directory instead? 
We could create a different directory for all other challenges that shouldn't be included?

**Comment by paralax** [comment]
yeah we could do that. give it a whirl?

some are mine but not yet ready for publication, most not included are
third party for which i have no right to publish (per terms of reddit), but
put there for my own management of future challenges.
- jose

On Fri, Apr 1, 2016 at 3:17 PM, Joe Reynolds notifications@github.com
wrote:

> If they're not meant to be included can we not remove them from the
> directory instead?
> We could create a different directory for all other challenges that
> shouldn't be included?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/paralax/ColossalOpera/issues/33#issuecomment-204529942

## 

jose nazario
For Privacy Act and Paperwork Reduction Act Notice, see page 2

**Comment by joereynolds** [comment]
Cool, I'll give it a go at some point. How can I tell which ones can't be published? Are they the ones with ZZ at the start?

**Comment by paralax** [comment]
The zz ones have been used and can be published. The ones that can't be are
first not included in the makefile and second usually have someone else in
the credits. But not exclusively. Eg some I wrote (so no credits) but
they're not ready like museum cameras 2.

Jose

Sent from my Motorola Razor

On Apr 1, 2016, at 5:13 PM, Joe Reynolds notifications@github.com wrote:

Cool, I'll give it a go at some point. How can I tell which ones can't be
published? Are they the ones with ZZ at the start?

**Comment by joereynolds** [comment]
All done, PR is up
